name: check-project
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # check – произвольно выбранное имя задания
  # их может быть больше одного
  check:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    # список шагов, которые надо выполнить
    steps:
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
      # run – произвольная bash-команда
      # сетап проекта
      - run: make setup
      # запуск тестов
      - run: make test
      # запуск линтера
      - run: make lint
